### ISSUE TITLE
[Feature request] Allow scripts on specific domains

### ISSUE THREAD

**Issue by RyanPWalker** [tksugimoto/chrome-extension_open-local-file-link#10]
This extension works on clicking files, but it'd be great if it allowed scripts to run on localhost pages too.  For example: `<script src="file://Users/me/repo/index.js"></script>` is blocked by chrome.

**Comment by tksugimoto** [comment]
It is not possible to read a local `file://` from a `http(s)://` page with a `<script>` tag.

It is better to start http server locally so that it looks like `<script src="http://localhost/me/repo/index.js"></script>`.
