### ISSUE TITLE
Extension throws content_script.js:2 Uncaught TypeError: Cannot read property 'addEventListener' of null     at content_script.js:2

### ISSUE THREAD

**Issue by wald-tq** [tksugimoto/chrome-extension_open-local-file-link#12]
Extension throws following error message in chrome console:

content_script.js:2 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at content_script.js:2
(anonymous) @ content_script.js:2

**Comment by tksugimoto** [comment]
@wald-tq 
Thank you for reporting the Issue.

On what pages are exceptions thrown?
I have never seen.

I want to know the reason for the exception and check if a non-null check on `document.body` is sufficient.

```diff
+	if (document.body) {
		document.body.addEventListener('click', evt => {
```

**Comment by wald-tq** [comment]
Hi @tksugimoto,

mostly on localhost while developing webapplications and using the console.

**Comment by wald-tq** [comment]
Thanks @tksugimoto for the release. Can confirm, that the errors are gone.
