### ISSUE TITLE
Port it to Edge Store

### ISSUE THREAD

**Issue by snooky-ch** [tksugimoto/chrome-extension_open-local-file-link#17]
Hi Takashi

Is it possible to port your extension to the Microsoft Edge store?
https://microsoftedge.microsoft.com/addons
https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension

I know, normally you can install it form the Chrome store, but some Group Policy Rules can deny it.

I don't want to use your work and add it to the Edge store myself.

Thank you and best regards

**Comment by tksugimoto** [comment]
I think it's a good idea to publish it to the Edge store.

It seems that the extension can be ported with almost no changes.

However, when I tried it, I gave up the transplant for the following reasons.

- An error occurred when registering a Microsoft developer account
- (First time only) Registration fee will be charged
- There seems to be few people who can only use Edge and are restricted by GPO
  - I feel that it is not good to use the loophole that the Chrome store is restricted but the Edge store can be used. I think it's better to move to have the restrictions on GPOs relaxed.
