### ISSUE TITLE
Broken in latest chrome update?

### ISSUE THREAD

**Issue by pbreheny** [tksugimoto/chrome-extension_open-local-file-link#24]
This extension has always worked flawlessly for me in the past -- thank you for developing it! However, it seems to no longer function now with the latest update to Chrome:

Version 118.0.5993.70 (Official Build) (64-bit)

This just happened in the past 3 days or so. I've replicated this behavior on two different machines (when you click on a local link, nothing happens).

**Comment by PolarBaehr** [comment]
Having the same issue. Hoping for an update soon.

**Comment by tksugimoto** [comment]
I also confirmed it.
I will try to deal with it.

## Related Documents
- [What's new in Chrome extensions - Chrome for Developers](https://developer.chrome.com/docs/extensions/whatsnew/#changes-to-file-scheme)
    > **Chrome 118: Changes to opening file: scheme URLs**
    > Beginning in Chrome 118, extensions will need the "Allow access to file URLs" setting enabled from the chrome://extensions page to open file:// scheme URLs using the [Tabs](https://developer.chrome.com/docs/extensions/reference/tabs/) or [Windows](https://developer.chrome.com/docs/extensions/reference/windows/) APIs.
- [Restricting use of file: URLs in tabs and windows APIs](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/ZtCvVISQU54/m/tOjjlzkfAgAJ?pli=1)
- https://github.com/w3c/webextensions/issues/426
