### ISSUE TITLE
Latest v0.9.3 still not allow local file access in Edge browser

### ISSUE THREAD

**Issue by mushu999** [tksugimoto/chrome-extension_open-local-file-link#28]
Even in the latest v0.9.3 version the option to "Allow access to file URLs" in the Edge version needs to be implemented in Edge browser.

**Comment by tksugimoto** [comment]
I confirmed that the "Allow access to file URLs" option exists in Edge 118.0.2088.69.

Enabling this option requires user operation for security reasons, and cannot be turned on automatically from the extension side.
