### ISSUE TITLE
Override style

### ISSUE THREAD

**Issue by groschatchauve** [tksugimoto/chrome-extension_open-local-file-link#4]
Another question. Is it possible to modify CSS of a directory view in Chrome ?

If you are interested, your extension could propose some themes (CSS stylesheet) to improve directories views ?

In this case, I would appreciate to contribute.

**Comment by tksugimoto** [comment]
> Is it possible to modify CSS of a directory view in Chrome ?

Yes, you can use following settings.

`manifest.json`
```json

	"content_scripts": [{
		"all_frames": true,
		"matches": [
			"file:///*"
		],
		"css": [
			"sample.css"
		]
	}],
```

> If you are interested, your extension could propose some themes (CSS stylesheet) to improve directories views ?

No, I think that it is out of this extension's function.
If I make it, I will make it with another extension.
However, I am not dissatisfied with the appearance at the present time.

**Comment by groschatchauve** [comment]
Thanks for the response.
So, the solution is simple.

Even if I am quite satisfied too, other people are not satisfied in my company. So I need this enhancement. I will probably do my own extension using yours, if you agree. But I won't publish it.

**Comment by tksugimoto** [comment]
> So I need this enhancement. I will probably do my own extension using yours, if you agree. But I won't publish it.

Although it does not matter, I think it would be better to reduce the function of each extension by creating an extension that only modifies the CSS of  a directory view.

**Comment by groschatchauve** [comment]
I agree with you. But lots of people are afraid to set up lots of browser extensions in companies. Anyway, it's not so important.
