### ISSUE TITLE
How to read files from a file:// path dragged on chrome new tab

### ISSUE THREAD

**Issue by cksachdev** [tksugimoto/chrome-extension_open-local-file-link#9]
Is it possible to list all the files from a local file path? I have set the permission as "*://*/*" but couldn't figure out a way to list all files e.g. filter all mp4 and create a playlist.

**Comment by tksugimoto** [comment]
@cksachdev 

> Is it possible to list all the files from a local file path?

This Chrome extension can't do that.

Isn't it better to use a media player?
If you want to make your own, you should use Node.js instead of a browser.

- [Node.js](https://nodejs.org/en/)
   - [File System | Node.js v13.0.1 Documentation](https://nodejs.org/api/fs.html)
